version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: node-appv2
    container_name: youthful_blackburn_v2
    command: npm start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  postgres:
    image: postgres
    volumes:
      - data-volume:/data/db
    ports:
      - "5432:5432"
    networks:
      - app-network
  client:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: react-appv2
    container_name: adoring_hoover_v2
    command: npm start
    volumes:
      - ./ui/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    env_file: ./ui/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
